# Generated by Django 2.2.4 on 2019-08-14 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(upload_to='static/users/avatars/')),
                ('is_investor', models.BooleanField()),
                ('birth_date', models.DateField()),
                ('education', models.CharField(max_length=600)),
                ('residence', models.CharField(max_length=400)),
                ('bio', models.CharField(max_length=1500)),
                ('profiles', models.CharField(max_length=200)),
                ('tags', models.ManyToManyField(to='api.Tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('preview', models.FileField(upload_to='static/pitches/previews/')),
                ('description', models.CharField(max_length=1500)),
                ('video', models.FileField(upload_to='static/pitches/videos/')),
                ('presentation', models.FileField(upload_to='static/pitches/presentations/')),
                ('necessary_investitions', models.IntegerField()),
                ('smartid', models.CharField(max_length=400)),
                ('investors_interested', models.ManyToManyField(related_name='investors_interested', to=settings.AUTH_USER_MODEL)),
                ('investors_signed', models.ManyToManyField(related_name='investors_signed', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='api.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
