# Generated by Django 2.2.4 on 2019-08-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
