# Generated by Django 2.2.4 on 2019-08-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190824_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='presentation',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='preview',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='video',
            field=models.CharField(max_length=1000),
        ),
    ]
