# Generated by Django 2.2.4 on 2019-09-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190824_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='presentation',
            field=models.FileField(upload_to='static/pitches/presentations/'),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='preview',
            field=models.FileField(upload_to='static/pitches/previews/'),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='video',
            field=models.FileField(upload_to='static/pitches/videos/'),
        ),
    ]
